name: CI for Spotify Ultimate Recap App

on:
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/app-ci.yml'


env:
  CI: true

defaults:
  run:
    working-directory: app

jobs:
  check:
    name: Build & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
